config/routes.rb
NewsViewer::Application.routes.draw do
  get 'tweets/index'
  get 'tweets/fetch'
  get 'tweets/favorites'
  post 'tweets/toggle_favorite'

  root :to => 'tweets#index'
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  attr_accessible :tweet_id
  validates_uniqueness_of :tweet_id, :on => :create, :message => "must be unique"
  belongs_to :tweet

  class << self
    def toggle(tweet_id)
      if record = self.find_by_tweet_id(tweet_id)
        record.destroy
      else
        record = self.create(tweet_id: tweet_id)
      end
    end
  end

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  attr_accessible :text, :tweet_id, :created_at
  has_one :favorite
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_filter :set_metadata, only: [:index, :favorites]

  def index
    @tweets = Twitter.user_timeline(Settings.twitter[:watch_user])
  end

  def favorites
    @tweets = Twitter.statuses(Favorite.pluck(:tweet_id))
  end

  def fetch
    @tweets = Twitter.user_timeline(Settings.twitter[:watch_user], params)
    result = @tweets.map do |tweet|
      next if tweet.id == params[:max_id].to_i
      next if tweet.id == params[:since_id].to_i
      render_to_string(:partial => "tweets/tweet", :layout => false, :locals => {:tweet => tweet})
    end
    return render(text: result.join)
  end

  def toggle_favorite
    Favorite.toggle(params[:tweet_id])
    return render json: {status: 'ok'}
  end

private
  def set_metadata
    @metadata = Twitter.user(Settings.twitter[:watch_user])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper

  def favorite_class(tweet_id)
    'favorite' if favorite_tweet?(tweet_id)
  end

  def favorite_tweet?(tweet_id)
    @favorite_ids ||= Favorite.pluck(:tweet_id)
    @favorite_ids.include?(tweet_id)
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title NewsViewer
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    .container
      .row
        .span3
        .span6=yield
        .span3

app/views/tweets/_tweet.haml
.tweet{"data-tweet-id" => tweet.id, "class" => favorite_class(tweet.id) }
  .star
    .star_icon
  .date= time_ago_in_words tweet.created_at
  .text= tweet.text

app/views/tweets/favorites.haml
%h1
  = image_tag(@metadata.profile_image_url)
  = @metadata.name + " Favorites"

%ul.nav.nav-tabs
  %li=link_to 'Feed', root_path
  %li.active=link_to 'Favorites', tweets_favorites_path

#tweets_list.favorites_list
  - @tweets.each do |tweet|
    = render 'tweet', tweet: tweet

app/views/tweets/index.haml
#refresh.refresh
  .refresh_icon
  %p.hint Refresh
%h1
  = image_tag(@metadata.profile_image_url)
  = @metadata.name + " tweets feed"

%ul.nav.nav-tabs
  %li.active=link_to 'Feed', root_path
  %li=link_to 'Favorites', tweets_favorites_path

#tweets_list
  - @tweets.each do |tweet|
    = render 'tweet', tweet: tweet
%p
  #more_tweets.btn.btn-large.btn-primary.btn-block Load more tweets